spin_manifest_version = 2

[application]
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
version = "0.1.0"

[application.trigger.amqp]
address = "{{address}}"
username = "{{username}}"
password = "{{password}}"

[[trigger.amqp]]
id = "trigger-{{project-name | kebab_case}}"
component = "{{project-name | kebab_case}}"
topic = "{{queue}}"

[component.{{project-name | kebab_case}}]
source = "target/{{project-name | kebab_case}}.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["{{address}}"]
[component.{{project-name | kebab_case}}.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]
